version: '3'

services:
  product_api:
    image: python
    ports:
      - 8082:8082
    volumes: 
      - .:/src
    environment:
      - PACT_BROKER_URL
      - PACT_BROKER_TOKEN
    working_dir: /src
    command: tail -f /dev/null  
